version: '3.8'

services:

  wiremock:
    image: wiremock/wiremock:2.34.0
    container_name: lagom_wiremock
    ports:
      - "10000:10000"
    command: "--verbose --port 10000"
    volumes:
      - ./wiremock:/home/wiremock

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./docker/grafana/dashboards/dashboards.json:/etc/grafana/provisioning/dashboards/dashboards.json

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'